- name: catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable default Node.js module
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user: 
     name: roboshop
     
  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application code inside app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Unzip/extract catalogue.zip /catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip 
      dest: /app
      remote_src: yes


