- name: catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable default Node.js module
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user: 
     name: roboshop
     
  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application code inside app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Unzip/extract catalogue.zip /catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip 
      dest: /app
      remote_src: yes

  - name: install npm dependencies in /app
    ansible.builtin.command: npm install # --> telling to install npm ( we can use both shell or command )
    args:
      chdir: /app # these 2 lines are == cd app (changing directory to /app)

  - name: copying catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: loading the service - daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

    #we are suppose to enable and start daemon here, but before that we are loading some data first because there are some chances to get error. 

  - name: copying mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

      #next task is loading schema : 
      # once we load the schema data, and run the same thing again (loading data) we get error saying that duplicate keys. 


