- name: catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable default Node.js module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable Node.js 18 module
    ansible.builtin.command: dnf module enable nodejs:18 -y
